# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 262dcb7793bee3edc084a4c92672f3500c9b654a60021bd5fe5db531a2fff03bb09e0b75eab71bab33b4e90cdbcc27b01946e4933da2a02e32d7cfb1d9139b7f

test:
  secret_key_base: 635a745fd2b2dfa62ae7c595e44db244f429dc93902b11c2fe79c4d87ce52181313f960fb604f019ac7fade21b002ee45900328afcc03de5a66116f94bb13eb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
